metricbeat.config:
  modules:
    path: ${path.config}/modules.d/*.yml
    # Reload module configs as they change:
    reload.enabled: true

monitoring:
  enabled: true

metricbeat.modules:

  # Docker monitoring
  - module: docker
    metricsets:
      - "container"
      - "cpu"
      - "diskio"
      - "healthcheck"
      - "info"
      #- "image"
      - "memory"
      - "network"
    hosts: ["unix:///var/run/docker.sock"]
    period: 10s
    enabled: false

    # Elasticsearch monitor
  - module: elasticsearch
    xpack.enabled: true
    period: 10s
    hosts: ["http://es:9200"]

  # Logstash monitor
  - module: logstash
    metricsets:
      - node
      - node_stats
    period: 10s
    hosts: ["ls:9600"]
    xpack.enabled: true

  # Kibana monitor
  - module: kibana
    metricsets:
      - stats
    period: 10s
    hosts: ["kib:5601"]
    xpack.enabled: true

  # Zookeeper monitor
  - module: zookeeper
    enabled: true
    metricsets: ["mntr", "server"]
    period: 10s
    hosts: ["zookeeper:2181"]

  # Kafka monitor
  - module: kafka
    metricsets:
      - consumergroup
      - partition
    period: 10s
    hosts: ["kafka:9092"]
    client_id: metricbeat

  # Metrics collected from a Kafka broker using Jolokia
  - module: kafka
    metricsets:
      - broker
      - consumer
      - producer
    period: 10s
    hosts: ["kafka:8778"]

output:
  # Save metrics in a dedicated es index
  elasticsearch:
    hosts: ["es:9200"]
    ilm.enabled: true
    ilm.rollover_alias: "metricbeat"
    ilm.pattern: "{now/d}-000001"

# Only for loading default dashboards
setup.kibana.host: "http://kib:5601"
setup.dashboards.enabled: false #enable first time to load dashboards
